name = "rawoutput"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "raw-output
database_id = "fdcbb9b8-dc7b-4837-ac0c-e57c46346c9b"
